FROM python

RUN pip install --upgrade pip 
RUN pip install openpyxl && pip install requests && pip install pyyaml && pip install pymysql
RUN pip install nornir && pip install nornir_napalm && pip install nornir_utils && pip install nornir_table_inventory && pip install nornir_netmiko && pip install napalm_h3c_comware
RUN pip install neo4j
